# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
        - task: NexPloitScan@3
          inputs:
            apiToken: 'uqa8i6x.nexp.pfyogr58ptwfozw8f0743o4tehlzmnvx'
            hostname: 'nexploit.app'
            module: 'dast'
            discoveryTypes: 'crawler'
            crawlerUrls: 'https://brokencrystals.com/'
            scanTests: 'angular_csti,jwt,date_manipulation,cookie_security,csrf,directory_listing,dom_xss,file_upload,full_path_disclosure,header_security,http_method_fuzzing,secret_tokens,version_control_systems,wordpress'